<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net9.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
		<EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
		<AnalysisLevel>6.0-all</AnalysisLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<WarningLevel>9999</WarningLevel>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="SonarAnalyzer.CSharp" Version="10.20.0.135146">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\VittaController\VittaController.csproj" />
		<ProjectReference Include="..\VittaModel\VittaModel.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\data\users.csv">
			<Link>data\users.csv</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\..\data\foods.csv">
			<Link>data\foods.csv</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Include="..\..\data\menus.csv">
			<Link>data\menus.csv</Link>
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>